name: Test Docker Compose

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start containers
        run: |
          docker compose up -d --build
          echo "Waiting for services to start..."

      - name: Wait for Debezium Connect
        run: |
          for i in {1..10}; do
            if docker compose logs debezium-connect | grep "Started ConnectorTask"; then
              echo "Debezium Connect is ready!"
              exit 0
            fi
            sleep 10
          done
          echo "Debezium Connect failed to start in time"
          exit 1

      - name: Check service status
        run: |
          docker ps -a
          docker compose ps -a
          docker compose logs

      - name: Test Debezium Connect health
        run: |
          echo "Checking Debezium Connect health..."
          curl -v --retry 5 --retry-delay 10 --retry-max-time 60 --fail http://localhost:8093/connectors

      - name: View logs if health check fails
        if: failure()
        run: |
          docker compose logs
          docker inspect $(docker compose ps -q)

      - name: Tear down containers
        if: always()
        run: docker compose down -v --remove-orphans