name: Test Docker Compose
on:
    push:
        branches: [master]
    pull_request: 
        branches: [main]

jobs:
    docker-compose-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Run Docker Compose
          run: |
            docker-compose up -d
            sleep 60
        - name: Check service health
          run: |
            docker ps
            # Check that  Debezium Connect is healthy
            curl --retry 5 --retry-delay 5 --fail http://localhost:8093/connectors || exit 1

        - name: Tear down containers
          if: always()
          run: docker-compose down -v